app:
  servicePort: 9898
  containerPort: 9898

deployment:
  memoryRequest: 50Mi
  cpuRequest: 10m
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

image:
  repository:
    name: ghcr.io/stefanprodan/podinfo
    isPrivate: false
    secretName: null
  name: podinfo
  tag: 6.5.1
  pullPolicy: Always