apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: apps
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: apps
  project: default
  source:
    path: charts/argocd-app-of-apps
    targetRevision: v0.2.2
    repoURL:  'https://github.com/rallyware/terraform-argocd-apps'
    helm:
      # valueFiles:
      #   - app-values.yaml
      values: |
        "applications":
          - "annotations": {}
            "automated":
              "allowEmpty": true
              "prune": true
              "selfHeal": true
            "chart": "charts/generic-app/"
            "clusterName": "in-cluster"
            "ignoreDifferences": []
            "managedNamespaceMetadata": null
            "name": "argo-cd-production-podinfo"
            "namespace": "apps"
            "omitFinalizer": false
            "path": ""
            "projectName": "aweasome-project"
            "releaseName": "podinfo"
            "repoURL": "https://github.com/b3outputs/helm-charts"
            "retry":
              "backoff_duration": "30s"
              "backoff_factor": 2
              "backoff_max_duration": "1m"
              "limit": 0
            "revisionHistoryLimit": 5
            "skipCrds": false
            "syncOptions":
            - "CreateNamespace=true"
            - "ApplyOutOfSyncOnly=true"
            - "ServerSideApply=true"
            "syncWave": 50
            "targetRevision": "generic-app-v0.1.6"
            "values":
            - |-
              app:
                servicePort: 9898
                containerPort: 9898

              deployment:
                memoryRequest: 50Mi
                cpuRequest: 10m
                strategy:
                  type: RollingUpdate
                  rollingUpdate:
                    maxUnavailable: 25%
                    maxSurge: 25%

              image:
                repository:
                  name: ghcr.io/stefanprodan/podinfo
                  isPrivate: false
                  secretName: null
                name: podinfo
                tag: 6.5.1
                pullPolicy: Always
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true


